### ISSUE TITLE
default_allocator allocate and deallocate method

### ISSUE THREAD

**Issue by RifsBoy** [Masstronaut/FTL#4]
The implementation of allocate and deallocate should not use the new[] and delete[] operators as they are standardly used for allocation/deallocation + construction/destruction, although they are used to create a char[]. This should be substituted for operator new and operator delete functions which solely allocates and deallocates memory.
More Info:
operator new, operator new[]: http://en.cppreference.com/w/cpp/memory/new/operator_new
operator delete, operator delete[]: http://en.cppreference.com/w/cpp/memory/new/operator_delete

**Comment by Masstronaut** [comment]
Resolved with PR #5
